### ISSUE TITLE
Use hashtag

### ISSUE THREAD

**Issue by Andsoeg** [raulrene/twitter-contest-js-bot#24]
Would be great if the bot could use hashtags when retweeting if it notices this. Many of my retweets require this in addition to the retweet itself. aslo some retweets require "Like comment and retweet."

**Comment by raulrene** [comment]
I don't think I fully understand. You mean something like "retweet to win #includeThisHashtag"? Like some contest owners require you to include the hashtag in the RT in order to be eligible?

I understand that some contests require more, but this is a Contest Bot based on retweets. It could be an improvement, though.

**Comment by Andsoeg** [comment]
Thats what i meant, yeah.

**Comment by raulrene** [comment]
For likes/comments I imagine it won't be very hard. The program would have to check for words like "comment" or "like". But what about hashtags? Most posts on Twitter use hashtags. But very few contest organizers actually require adding the hashtags in the RT. How do you know when to add hashtags and when not?

Furthermore, when you Retweet you can't change the text. So you would have to create a new tweet. I haven't seen anything like this and don't really consider it useful. If you could elaborate more or come up with an idea for it to work, that'd be great.

I could add an improvement for Liking and Commenting.
