### ISSUE TITLE
Bot only favoriting, not retweeting most tweets it finds

### ISSUE THREAD

**Issue by geepy123456790123** [raulrene/twitter-contest-js-bot#28]
With most (>90%) of the tweets the bot is finding, it's liking/favoriting them instead of retweeting them, even when the contest doesn't require favoriting.

**Comment by raulrene** [comment]
Can you take a screenshot of the console? Even of the Twitter account.

Does it output any error? This sounds weird. I'm saying this because the code for liking is called only after the retweet is done (something like <code>API.retweet(tweet_id).then -> { like(id) </code>). So it can't get to the like method until it retweeted. The console output for 'Liked Tweet #' will not be directly under the corresponding 'Retweeting Tweet #' because the latter is done async for faster processing. But the same remains: the code doesn't get there before attempting to Retweet.

**Comment by Killerherts** [comment]
ill check this tonight when i give this a run

**Comment by NanoPish** [comment]
Most of the tweets are blacklisted / ignored.
https://i.imgur.com/FBRx7F0.png

It blacklisted like 50 tweets but only retweeted 30, so it is not possible that they were already retweeted ?
